# Generated by Django 3.1.7 on 2021-03-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'publication',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='pizza',
            name='topping',
            field=models.ManyToManyField(related_name='pizaaes', related_query_name='pizza_query_set', to='myapp.Topping', verbose_name='所有配料'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('publications', models.ManyToManyField(to='myapp.Publication')),
            ],
            options={
                'db_table': 'article',
                'ordering': ['headline'],
            },
        ),
    ]
