# Generated by Django 3.1.7 on 2021-03-25 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210325_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='用户名')),
            ],
        ),
        migrations.CreateModel(
            name='MySpecialUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svipuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='svip', to='myapp.myuser')),
                ('vipuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.myuser')),
            ],
        ),
    ]
