EMAIL_VERIFY_URL_PREFIX = 'https://test/email/verify?'

MAX_ADDRESS_COUNT = 20

USER_BROWSER_HISTORY_KEY = 'history_'
USER_BROWSER_HISTORY_DELETE_MODEL = 0
USER_BROWSER_HISTORY_PUSH_START = 0
USER_BROWSER_HISTORY_PUSH_STOP = 4
